# Generated by Django 6.0 on 2025-12-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_detail',
            field=models.TextField(verbose_name='آدرس دقیق'),
        ),
    ]
