# Generated by Django 6.0 on 2025-12-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='زیرنویس')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='تصویر بنر')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک (اختیاری)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
            },
        ),
    ]
