# Generated by Django 6.0 on 2025-12-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('digital', 'کالای دیجیتال'), ('fashion', 'مد و پوشاک'), ('home', 'خانه و آشپزخانه'), ('beauty', 'زیبایی و سلامت'), ('toys', 'اسباب بازی'), ('other', 'سایر')], default='other', max_length=20, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت با تخفیف (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت اصلی (تومان)'),
        ),
    ]
