# Generated by Django 6.0 on 2025-12-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_category_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='هر ویژگی را در یک خط بنویسید', null=True, verbose_name='ویژگی\u200cهای کلیدی'),
        ),
    ]
