# Generated by Django 6.0 on 2025-12-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'موبایل'), ('laptop', 'لپ\u200cتاپ'), ('apparel', 'پوشاک'), ('home', 'خانه و آشپزخانه'), ('beauty', 'زیبایی و سلامت'), ('other', 'سایر')], default='other', max_length=20, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت با تخفیف (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت اصلی (تومان)'),
        ),
    ]
